# Dockerfile.backend

# Base image
FROM python:3.8-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY backend/ .

# Set environment variable for Flask
ENV FLASK_APP=app.py

# Run the application
# CMD ["python", "app.py"]

# Expose the port the app runs on
EXPOSE 5000

# Run the Flask application
CMD ["flask", "run", "--host=0.0.0.0"]